-- AlterEnum
ALTER TYPE "CreditReason" ADD VALUE 'PROMPT_ENHANCEMENT';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyEnhanceCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailyEnhanceResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
