// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Supabase's pgbouncer
    // transaction-mode pooler doesn't support the DDL/prepared statements Migrate uses.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
